version: '3'

services:
  php-client:
    image: php:7-alpine
    # image: mg-mg2-server_fpm
    volumes:
      - ./:/app
    working_dir: /app
    restart: always
    command:
      - /bin/sh
      - -c
      - |
        sleep 5
        php test/client.php
        # php test/client-elephant.io.php
    links:
      - node-server
    depends_on:
      - composer
      - node-server
  composer:
    image: composer
    volumes:
      - ./:/app
    working_dir: /app
    command:
      - /bin/sh
      - -c
      - |
        composer install
        composer dump-autoload --optimize
  node-server:
    image: node:12-alpine
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - DEBUG=*
    command: npm run dev
